// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drijoftroejrdlqhfdya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyaWpvZnRyb2VqcmRscWhmZHlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MzE5NDMsImV4cCI6MjA2NDIwNzk0M30.jWlZAwJe7dYtRCVbrN-7VgVgb5A4acWx1eSat7dgWEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);