// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Support both browser and Node.js environments
const isBrowser = typeof window !== 'undefined';

// Use environment variables for Supabase configuration
let SUPABASE_URL = 'https://xcfziysmpitxuenoclsg.supabase.co';
let SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjZnppeXNtcGl0eHVlbm9jbHNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NDQwMTksImV4cCI6MjA2NDIyMDAxOX0._YHmuhCD0nmjjtcQ0six10f5-MeuGjvfj5HSb_oisrY';

if (isBrowser) {
  // Browser environment - use import.meta.env
  SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || SUPABASE_URL;
  SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_KEY || SUPABASE_ANON_KEY;
} else {
  // Node.js environment - use process.env
  SUPABASE_URL = process.env.VITE_SUPABASE_URL || SUPABASE_URL;
  SUPABASE_ANON_KEY = process.env.VITE_SUPABASE_KEY || SUPABASE_ANON_KEY;
}

// Ensure we have values for URL and key
if (!SUPABASE_URL) {
  console.error('Supabase URL is required. Please check your environment variables.');
}

if (!SUPABASE_ANON_KEY) {
  console.error('Supabase key is required. Please check your environment variables.');
}

// Regular client with anonymous privileges (for client-side operations)
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);